language: node_js
node_js:
  - "10"

cache:
  yarn: true

script:
  - yarn lint
  - yarn test
  - yarn build
  - if [ "$TRAVIS_BRANCH" =  "master-main-site" ]; then gh-pages --repo https://$GITHUB_TOKEN@github.com/ravikp7/ravikp7.github.io.git -d build -b master; fi