language: node_js
node_js:
  - "10"

cache:
  yarn: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "./build"
  on:
    branch: master-main-site
  target_branch: "master"
